# Generated by Django 4.0.6 on 2022-07-20 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cost', models.PositiveIntegerField()),
                ('days', models.PositiveIntegerField()),
                ('nights', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('country', models.CharField(max_length=20)),
                ('free_places', models.PositiveIntegerField()),
                ('broned_tours', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
