# Generated by Django 4.0.6 on 2022-07-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_day',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_month',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
